### ISSUE TITLE
Deploy Preview Failures

### ISSUE THREAD

**Issue by HassanAbouelela** [discord-python/site#728]
We get occasional CI failures from the netlify preview deploys due to GitHub rate limits. [Example](https://app.netlify.com/sites/pydis-static/deploys/62b21f7a0849350009d6ce49):

```
Traceback (most recent call last):
  File "static-builds/netlify_build.py", line 122, in <module>
    download_artifact(*get_build_artifact())
  File "static-builds/netlify_build.py", line 36, in get_build_artifact
    pull_request.raise_for_status()
  File "/opt/buildhome/python3.8/lib/python3.8/site-packages/httpx/_models.py", line 1423, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/python-discord/site/pulls/727
For more information check: https://httpstatuses.com/403
```

This issue is meant for finding workarounds that allow us to avoid these issues, with the following limitations in mind:
1. We can't use action secrets, since those are not [accessible to external contributors](https://github.community/t/can-pull-requests-change-actions/143120).
2. We can't use any sensitive secrets in the netlify build, since the build script from the PR is executed with full trust. Assume any secrets in netlify are publicly visible.

**Comment by HassanAbouelela** [comment]
## Personal Access Tokens
This is an easy solution, and what the script used initially, but PATs aren't read-only, meaning they can make commits to any of our public repos that completely bypass any checks. This is a critical security flaw.

**Comment by HassanAbouelela** [comment]
## GitHub App
This seemed promising at first, since it has a much more robust permission system than PATs, and can be scoped per repo. However, accessing the API through an app is only meant to be performed by a secure backend server. You need to use a JWT generated within 10 minutes of the request. Generating the token requires access to the app's private key, which keeping in-line with limitation 2 makes this a no-go.

We can get around this issue by setting up a simple server that performs the intermediary steps that use the GitHub API, but this is not entirely in-line with our philosophy for CI. We deploy products, not tooling for developing those products. At that point though, a PAT would work too.

**Comment by HassanAbouelela** [comment]
## Netlify CLI
Not possible owing to limitation 1. You need a secret to deploy using the CLI. You also lose out on a lot of the nice features, since you can't manually deploy previews. You can only deploy actual deployments. This is not great for security. On top of that, we'd have to manually add a comment to the PR linking the build, which I believe requires a GitHub app running on a server, (see the previous comment for why that's not desirable). If we're running stuff on our server either way, I'd prefer the previous approach over this one.

**Comment by HassanAbouelela** [comment]
## Intermediary Build Server
Instead of asking the GitHub API for the data, we could have the action upload the result to a server we control, and expose those results without authentication or rate limiting issues. @ChrisLovering suggested using our ansible servers with [rsync](https://linux.die.net/man/1/rsync) for this purpose.

The following are not limitations, but considerations:
1. We can't have secrets here, owing to limitation 1, meaning the rsync server has to be unprotected
2. We need to always communicate to the build server *something*, since we need to know when to stop the netlify build. It's easy to imagine what this would be in the case of a passed build, but if a build fails, we still need to upload something to signal to netlify to error out.

**Comment by HassanAbouelela** [comment]
I've added all the solutions I could think of. If someone has any other ideas, please share them here.

**Comment by HassanAbouelela** [comment]
Interesting development: I've been told nightly should not be used for programmatic access. This seriously hinders the previews as I can't think of any other way to get the files from github to netlify. We might need a more drastic solution here.

**Comment by HassanAbouelela** [comment]
## Cloudflare Workers

A suggestion from Chris and Dorsan was to use cloudflare workers. There are two flavors to this suggestion:
- Upload the build output from actions to durable storage. This is a variation on [`Intermediary Build Server`](https://github.com/python-discord/site/issues/728#issuecomment-1162411051), which means it has the same problems that would have.
- Use a worker for the [`GitHub App`](https://github.com/python-discord/site/issues/728#issuecomment-1162406171) idea. This is a decent idea, but the problem is there's no benefit to doing this in a worker. Doing it somewhere such as our site API would make this approach more maintainable because we have about 20x more python developers than TS developers.
